### ISSUE TITLE
Unrecognized icons passed in the setup call cause nil index errors

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-navic#10]
Passing any icons that are not found in the internal map of icons to the icons key causes errors. This happens when say a user has a map of icons they use for lsp related things, and they pass this directly to navic to re-use the same icons they use e.g. with cmp. If the kind is unrecognized by navic the lookup will result in `nil` which is then directly used in a further lookup without a check for an empty value

https://github.com/SmiteshP/nvim-navic/blob/master/lua/nvim-navic/init.lua#L251-L254

e.g.
```lua
navic.setup({
  icons = {
    UnsupportedKey = "icon",
  }
})
```
The above will cause this error. Ideally it would just ignore any keys it doesn't recognize, so a custom object doesn't have to be created just for this plugin's setup.

**Comment by akinsho** [comment]
As a complete side note I've noticed that this plugin references to LSP kinds (e.g. Namespace, Null) that I haven't seen referenced before by other plugins like `cmp` or `lspkind` I wonder if it's just that those plugins omitted those kinds, or they are new? Since presumably you are getting them from the lsp, so they must be official so probably need to be added to those plugins?

**Comment by SmiteshP** [comment]
Yeah sure! I can add a check for this while setting up.

> As a complete side note I've noticed that this plugin references to LSP kinds (e.g. Namespace, Null) that I haven't seen referenced before by other plugins like cmp or lspkind I wonder if it's just that those plugins omitted those kinds, or they are new? Since presumably you are getting them from the lsp, so they must be official so probably need to be added to those plugins?

I am getting them from the official LSP specification. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolKind. It defines the number to kind mapping. I am not sure if these categories were added recently or not. But yeah, maybe they need to add these categories too. Not sure though.
