### ISSUE TITLE
I would like to see help tags on variables

### ISSUE THREAD

**Issue by CoralPink** [SmiteshP/nvim-navic#107]
Hi, sorry to keep coming back! 😅

Regarding the PR you asked for the other day… (https://github.com/SmiteshP/nvim-navic/pull/106)

If you try to refer to help as`:h depth_limit`, you will get the following.

`E149: Sorry, no help for depth_limit`

I thought the variable name in the help was probably just wrong,
but you had to specify it as a tag in the first place…

I'm not familiar with the help specs myself, so this is a vague suggestion,
but how about the following to solve this problem? 🤔

* Plan 1:
  Place tags as many other neovim plugins help do
```
                                               *navic-customise.icons*
icons: table
    Icons to show for captured symbols. Default icons assume that you
    have nerd-font.
```

* Plan 2:
  Tagging with maximum respect for the original text
```diff
*icons*: table
    Icons to show for captured symbols. Default icons assume that you
    have nerd-font.
```

(Sorry! the example changed from `depth_limit` to `icons`...😱)

**Comment by SmiteshP** [comment]
Adding tags for each option would be too much in my opinion. Also I don't see other plugins doing the same so I would also not want to do this.

**Comment by CoralPink** [comment]
I am sorry if I have offended you.
Of course, the author's opinion should be respected the most.

Thanks for taking the time to reply.

**Comment by SmiteshP** [comment]
Ah.. no offense taken. English isn't my first language 😓 , sorry if the previous message came of as offended.

**Comment by CoralPink** [comment]
Oh, no. Thank you for your concern. I am the one who doesn't understand English at all!
(I use a translation tool for everything 😅).

I look forward to seeing more progress on `nvim-navic` and `nvim-navbuddy` in the future! 🤗
