### ISSUE TITLE
Ignore subsequent attempts to attach to the same client if already attached

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-navic#11]
For many reasons including, reloading your nvim config, or some modules within it, restarting a language server etc. a user could trigger the on attach function of a language server several times which currently causes a warning message about trying to re-attach to an already attached client. I think this should just be ignored and if it is, then the level of the notification should be `debug` or `trace` so that only users wanting to see all notifications get these messages.

As a side note, it might be worth thinking about moving the `attach` to be handled automatically by using the `LspAttach` autocommand in nightly when that becomes stable. I believe it was added so plugins don't have to specifically depend on the user placing the specific function call in the on attach and allow plugins to detect when servers are attached to buffers themselves

**Comment by SmiteshP** [comment]
Yep! Will fix this to not show up for the same server. The main intention of that warning was to let people know that nvim-navic can make use of only one server attached to the buffer. So not to attach navic to multiple lsp for same the language.

> As a side note, it might be worth thinking about moving the attach to be handled automatically by using the LspAttach autocommand in nightly when that becomes stable. I believe it was added so plugins don't have to specifically depend on the user placing the specific function call in the on attach and allow plugins to detect when servers are attached to buffers themselves

Such a autocmd event would be useful! Thanks, I will look into it.

**Comment by cj** [comment]
@SmiteshP I am running the latest version and still run into this message: 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1819/207405086-8782754f-971c-407c-82f2-c77f1efaa481.png">

Is there a setting I need to enable?
