### ISSUE TITLE
JSX support?

### ISSUE THREAD

**Issue by AdamSitar** [SmiteshP/nvim-navic#113]
Hi, I love the the navbuddy extension, but one problem I have is that the nodes displayed do not index anything inside the return part of the function

This is how navbuddy structure looks like: 
![image](https://user-images.githubusercontent.com/68128060/235357783-0b910070-77d1-41f2-8b3d-742149c08ddb.png)

And this is how a different plugin (https://github.com/simrat39/symbols-outline.nvim) looks like:
![image](https://user-images.githubusercontent.com/68128060/235357611-c05d0907-8358-4e80-a1ae-2375f04f905c.png)

Looks like this plugin somehow indexes even the JSX, but not always, the behavior is not consistent - sometimes it works exactly like navic/navbuddy

I'm assuming that the navbuddy takes the data from navic, which gets them from the LSP - would it be possible to configure navic to index the JSX in the return part of the function also? 

Thanks!

**Comment by AdamSitar** [comment]
the PR that added the JSX functionality to the other plugin is this one:  https://github.com/simrat39/symbols-outline.nvim/pull/144

if that helps

**Comment by SmiteshP** [comment]
There was a similar issue opened on navbuddy https://github.com/SmiteshP/nvim-navbuddy/issues/11
I don't want to add anything language specific as it becomes a maintenance overhead. Also looks like they are using treesitter to get this data, which another thing I want to avoid. Hope you understand.
