### ISSUE TITLE
Allow highlighting separator differently to the text

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-navic#12]
Currently, the navic text shares the same highlight group as the separator, and so it isn't possible to make the separator visually distinct from the rest of the text. It would be great if the separator could use its own highlight group, e.g. `NavicSeparator` distinct from `NavicText`

Another side note 😅 I think it might be worth calling out quite loudly that a user is expected to set the `NavicIcon*` and `NavicText` etc. by themselves by maybe including an example  `highlight link NavicIconFunction Function`. This is not really related to the separator issue, I just thought for newer users they'll be confused to find that it talks about adding highlights but nothing is highlighted without further intervention on their part

**Comment by MordechaiHadad** [comment]
@akinsho you should give [heirline.nvim](https://github.com/rebelot/heirline.nvim) a try.
I have fully integrated nvim-navic, in around an hour or so.
![](https://p0rn.pro/AFanaticalAndHeavenlyOffer)

**Comment by akinsho** [comment]
@MordechaiHadad thanks, but I use my own winbar/statusline functionality, I could always manually construct the winbar using `get_data` which I already considered and was what I was doing with `nvim-gps` but out of the box `navic` is very close to what I need already the only thing that I want control over is the separator colour, having that be configurable separately is much easier than the faff of generating the whole thing just to change that

**Comment by SmiteshP** [comment]
Yep! Will add this Highlight group.

> Another side note sweat_smile I think it might be worth calling out quite loudly that a user is expected to set the NavicIcon* and NavicText etc. by themselves by maybe including an example highlight link NavicIconFunction Function. This is not really related to the separator issue, I just thought for newer users they'll be confused to find that it talks about adding highlights but nothing is highlighted without further intervention on their part

Agreed! I will add a code snippet to README of how to setup highlight groups. 👍🏽

**Comment by akinsho** [comment]
Just tried this out and it works great thanks 👍🏾
