### ISSUE TITLE
Lualine `on_click` support

### ISSUE THREAD

**Issue by Mayrixon** [SmiteshP/nvim-navic#126]
I noticed that Navic has its own click support and provided a simple way to add a component in Lualine. Is that possible to expose an API to set up Navic click function when enabled as a Lualine component?

**Comment by SmiteshP** [comment]
Both the things are independent of each other. So just having click=true in setup function and adding navic component to lualine should work just fine

**Comment by Mayrixon** [comment]
Thanks @SmiteshP for your reply. I have tried with the option `click = true` of Navic inside a winbar of Lualine, and the click function works properly.
