### ISSUE TITLE
context not reset

### ISSUE THREAD

**Issue by ChristianChiarulli** [SmiteshP/nvim-navic#128]
The context does not reset when leaving a buffer with no context information then entering a buffer with context information then reopening the buffer with no context information.

<img width="684" alt="image" src="https://github.com/SmiteshP/nvim-navic/assets/29136904/64752a14-ae0a-44e7-8d7f-00c03794b57c">

<img width="874" alt="image" src="https://github.com/SmiteshP/nvim-navic/assets/29136904/070855da-59ba-4108-83cb-5b7941782aac">

<img width="633" alt="image" src="https://github.com/SmiteshP/nvim-navic/assets/29136904/ba9e5c45-8663-41bf-9f5f-26d23e7c7784">

**Comment by SmiteshP** [comment]
Hi @ChristianChiarulli !
This bug should now be fixed on latest master commit 👍🏽
