### ISSUE TITLE
Error after restarging LSP

### ISSUE THREAD

**Issue by arsham** [SmiteshP/nvim-navic#13]
After restarting the LSP server while it is attached to a buffer, I get these errors when moving the cursor:

```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/nvim-navic/lua/nvim-navic/init.lua:12: attempt to index a nil value
stack traceback:
        .../site/pack/packer/opt/nvim-navic/lua/nvim-navic/init.lua:12: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1704: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1173: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Please let me know if you need more information.

Thank you!

**Comment by SmiteshP** [comment]
Hey @arsham !
Are you using the latest commit? I am not getting this error. I have made a few changes today that might have fixed this issue.

**Comment by arsham** [comment]
I just updated to the latest version and the problem persists. This is the part of the config that attaches to the buffer:
```lua
local navic = require("nvim-navic")
local attach_wrap = function(client, ...)
  on_attach(client, ...) -- <- this would be my on_attach implementation
  local caps = client.server_capabilities
  if caps.documentSymbolProvider then
    navic.attach(client, ...)
  end
end
```
I am looping through all server configurations and assign the `attach_wrap` function to the client's `on_attach` property.

I can confirm this behaviour happens on sumneko and gopls LSPs. Also there are no notifications for unsupported documentSymbol (related to Null-LS).

**Comment by dsully** [comment]
I'm seeing this as well.

**Comment by SmiteshP** [comment]
I am still not able to reproduce this issue 😞 . Could you try attaching just nvim-navic and to lsp-servers? Also, is there any specific language you are facing this issue for?

As a sidenote, I would not recommend passing navic.attach like this. Some lsp servers that haven't updated to latest lsp spec would also return true for documentSymbolProvider and get attached. And then nvim-navic will complain about it sending older format of data.

>Also there are no notifications for unsupported documentSymbol (related to Null-LS).

That's probably because it is getting filtered out at `if caps.documentSymbolProvider`

**Comment by SmiteshP** [comment]
Also could you try adding the following lines of code below line 11
```lua
vim.pretty_print(symbols)
vim.pretty_print(client_id)
```
and tell me output before and after LspRestart?

**Comment by arsham** [comment]
I am using `gopls` in this case, but I've noticed it also happens on `sumneko`.

> As a sidenote, I would not recommend passing navic.attach like this. Some lsp servers that haven't updated to latest lsp spec would also return true for documentSymbolProvider and get attached. And then nvim-navic will complain about it sending older format of data.
> 

You are correct. After creating this issue I faced that problem and had to filter out a few servers.

The `client_id` before and after restart is `2`. This is the content of the `symbols` after restart:

<details>
<summary>Details</summary>

```lua
{
  [3] = {
    result = { {
        detail = "untyped string",
        kind = 14,
        name = "XXXX",
        range = {
          end = {
            character = 1,
            line = 35
          },
          start = {
            character = 0,
            line = 27
          }
        },
        selectionRange = {
          end = {
            character = 20,
            line = 28
          },
          start = {
            character = 1,
            line = 28
          }
        }
      }, 
      {}, -- and many more
    }
  }
}
```
</details>

Before restart the index reads `[2]`. I'm guessing you wanted to confirm that.

**Comment by dsully** [comment]
`sumneko` here for me. Haven't seen it in `pyright`.

**Comment by SmiteshP** [comment]
@arsham @dsully 
Could you try the bug-fix branch and let me know if it helps? After LspRestart try chaning some code around as well and let me know if navic is showing proper context info.

You can try out that branch like this
```lua
use {
    "SmiteshP/nvim-navic",
    branch = "bug-fix"
}
```

Will merge it if it fixes the issue

**Comment by arsham** [comment]
Thank you for the fix. It works!

**Comment by dsully** [comment]
Working for me as well. Thanks!
