### ISSUE TITLE
nvim-navic not working due to recent commit

### ISSUE THREAD

**Issue by jackfranklin** [SmiteshP/nvim-navic#130]
I did an update to my plugins today and noticed that nvim-navic was no longer showing anything as I navigated through a TypeScript project. I then also confirmed it wasn't working in a Lua project either.

I did some checking of commits and as of https://github.com/SmiteshP/nvim-navic/commit/e6da6f74d89de65258ea7e98e22103ff5de6dcf5, it was working just fine. Will continue to try recent commits to see if I can hunt down the issue.

**Comment by jackfranklin** [comment]
Don't ask me why as I have no idea, but if I checkout the next commit https://github.com/SmiteshP/nvim-navic/commit/0f2732e695af43b6fc07e5bd0cde66b4a54dfee1, it breaks, even though that commit is only formatting!

**Comment by jackfranklin** [comment]
Ah thank you @ChristianChiarulli, I didn't spot that. I have sent #131 which fixes it for me locally.

**Comment by augustocdias** [comment]
The `is_available` function is returning false all the time as well.

**Comment by SmiteshP** [comment]
Apologies guys, I merged a PR without testing it locally first 🙈

**Comment by leon-richardt** [comment]
Sorry everyone, this one is one me! It's beyond me how I made that change and didn't notice after.
