### ISSUE TITLE
Nvim-navic gives error for html file

### ISSUE THREAD

**Issue by zootedb0t** [SmiteshP/nvim-navic#15]
![nvim-navic](https://user-images.githubusercontent.com/62596687/173670592-2ffab8eb-5daf-4379-a0da-e607c142deb2.png)

**Comment by danielnehrig** [comment]
this error is unrelated to plugin itself but is a issue with your config.
only attach the plugin if the lsp supports documentSymbols

**Comment by zootedb0t** [comment]
Okay

**Comment by SmiteshP** [comment]
@zootedb0t Unfortunately html server hasn't kept up with updated LSP specification. There is nothing nvim-navic can do here. You could try opening a issue on html server's repo to updated documentSymbol fromat
