### ISSUE TITLE
Option to silent operation when LSP doesn't support required features

### ISSUE THREAD

**Issue by augustocdias** [SmiteshP/nvim-navic#22]
I use null-ls for linters, diagnostics and formatting for some filetypes and nvim-navic always pops up an error notification saying the server doesn't support `documentSymbols`. Would be nice to have an option to silence this kind of notifications.

**Comment by rudotriton** [comment]
I think that's what #14 is about

**Comment by NFrid** [comment]
you can attach navic only if client has this capability, like that:
```lua
  if client.server_capabilities.documentSymbolProvider then
    navic.attach(client, bufnr)
  end
```
