### ISSUE TITLE
feature request: pass buffer to `get_location` / `get_data`

### ISSUE THREAD

**Issue by 0xAdk** [SmiteshP/nvim-navic#29]
Currently when I try and use navic's get_location in my winbar it always returns the location for the current active buffer.
Obviously it should be returning the location for the buffer that has the winbar; though that doesn't seem possible with the current code...

I was able to make a simple patch to the code to get this working for me in the mean time.
Not sure if you think this is good enough though since it's a breaking change.
```diff
diff --git a/lua/nvim-navic/init.lua b/lua/nvim-navic/init.lua
index 3ce68ed..25d6dcd 100644
--- a/lua/nvim-navic/init.lua
+++ b/lua/nvim-navic/init.lua
@@ -284,8 +284,8 @@ function M.setup(opts)
 end
 
 -- returns table of context or nil
-function M.get_data()
-	local context_data = navic_context_data[vim.api.nvim_get_current_buf()]
+function M.get_data(bufnr)
+	local context_data = navic_context_data[bufnr ~= 0 and bufnr or vim.api.nvim_get_current_buf()]
 
 	if context_data == nil then
 		return nil
@@ -305,11 +305,12 @@ function M.get_data()
 	return ret
 end
 
-function M.is_available()
-	return vim.b.navic_client_id ~= nil
+function M.is_available(bufnr)
+	bufnr = bufnr ~= 0 and bufnr or vim.api.nvim_get_current_buf()
+	return vim.b[bufnr].navic_client_id ~= nil
 end
 
-function M.get_location(opts)
+function M.get_location(bufnr, opts)
 	local local_config = {}
 
 	if opts ~= nil then
@@ -339,7 +340,7 @@ function M.get_location(opts)
 		local_config = config
 	end
 
-	local data = M.get_data()
+	local data = M.get_data(bufnr)
 
 	if data == nil then
 		return ""

```

**Comment by SmiteshP** [comment]
> Obviously it should be returning the location for the buffer that has the winbar; though that doesn't seem possible with the current code...

Hi @0xAdk
For me the winbar shows the correct context for its respective window.

https://user-images.githubusercontent.com/43147494/177077978-b09132e7-28e6-489d-8674-f3adfe76882a.mp4

I am not sure I understand your issue correctly though. What problem are you trying to fix with this patch?

**Comment by SmiteshP** [comment]
In the above example I have setup the winbar as follows

```lua
require("feline").winbar.setup {
	components = {
		active = {
			[1] = {{
				provider = function()
					local text = navic.get_location()
					if #text ~= 0 then
						return '> '..text
					else
						return ''
					end
				end,
				enabled = function() return navic.is_available() end,
				right_sep = function() return { str = ' ', hl = mode_color().c } end,
				hl = function() return mode_color().c end
			}}
		},
		inactive = {
			[1] = {{
				provider = function()
					local text = navic.get_location()
					if #text ~= 0 then
						return '> '..text
					else
						return ''
					end
				end,
				enabled = function() return navic.is_available() end,
				right_sep = function() return { str = ' ', hl = mode_color().c } end,
				hl = function() return mode_color().c end
			}}
		}
	}
}

```

**Comment by 0xAdk** [comment]
this small snippet is enough to produce the bug for me
```lua
_G.winbar_func = function()
	return require 'nvim-navic'.get_location()
end

vim.opt.winbar = '%!v:lua.winbar_func()'
```
> What problem are you trying to fix with this patch?

I'm able to explicitly tell navic which buffer I want the data from instead of letting navic (incorrectly) guess

**Comment by SmiteshP** [comment]
Ok, I see the bug occuring with this snippet... the winbar gets updated just before switching window and thus displays wrong context

https://user-images.githubusercontent.com/43147494/177087334-6009a846-d503-4749-a3d2-be0cb9646b72.mp4

**Comment by SmiteshP** [comment]
Read through the docs and found this part 

> Note that the "%!" expression is evaluated in the context of the
current window and buffer, while %{} items are evaluated in the
context of the window that the statusline belongs to.

So if you use the following method to setup your winbar everything work should expected

```lua
_G.winbar_func = function()
	return require 'nvim-navic'.get_location()
end

vim.opt.winbar = '%{%v:lua.winbar_func()%}'
```

**Comment by spywhere** [comment]
This still breaking when the same file is being split into 2 windows though.

**Comment by gegoune** [comment]
Breaks for me too. I can have different positions reported for the same buffer that is opened in two windows, but as soon as I change windows position of a previous window changes to that of now current window.

Position of previous window does not change when scrolling through new window.

Hope it makes sense. Perhaps get_* should return for both buffer and window number? @SmiteshP Does it warrant new issue or should this one be reopened?
