### ISSUE TITLE
Feature request: add option to silence errors

### ISSUE THREAD

**Issue by smjonas** [SmiteshP/nvim-navic#36]
Hi, would you be interested in adding a `silence_errors` configuration option? I often get an error in files like Python files (like `nvim-navic: Server "pylsp" does not support documentSymbols, it responds with SymbolInformation format which has been deprecated in latest LSP specification.`) which quickly becomes annoying when opening certain files.

With this option set to `true`, it would simply show no errors and no context.

**Comment by SmiteshP** [comment]
Set `vim.g.navic_silence = true`
However, In your case the proper way to solve this issue would be to not pass navic.attach to pylsp's on_attach function.
