### ISSUE TITLE
[Bug] Navic errors if there is a missing name for a symbol

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-navic#37]
Whilst working with `ccls` in an objc `.m` file I encountered the following error

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/22454918/178349485-7bbda729-fab8-4edb-9bb7-57a9ec149f25.png">

It appears that the `name` field is missing, this seems to be an unexpected response for the language server. I have no idea why it does this, but Ideally this should be silently ignored. Since this is just a nice to have and any error in the winbar or statusline is retriggered on every redraw with leads to blocking nvim completely

**Comment by SmiteshP** [comment]
Hmm.. It is indeed an unexpected response. According to LSP spec `name` field should always be there. Anyways I will add a check to handle this. But it might be worth opening a issue on repo of ccls.
