### ISSUE TITLE
Highlight not applied for last character

### ISSUE THREAD

**Issue by irfanbacker** [SmiteshP/nvim-navic#41]
![Screenshot from 2022-07-15 17-52-19](https://user-images.githubusercontent.com/42970959/179222173-230c0c64-7335-4741-917e-251058f9eb7c.png)
As shown in the above image, There is a last character to which the highlight isn't applied to. Moreover, it seems to apply some other color. This color doesn't show up when navic is removed. I have set bg for all highlights mentioned in the readme as black.

**Comment by SmiteshP** [comment]
Can you share which statusline plugin are you using?
Also share the output of `set statusline?`

**Comment by irfanbacker** [comment]
I'm using lualine along with navarasu/onedark.nvim theme.

Output of `set statusline`:
```
statusline=%{%v:lua.require'lualine'.statusline()%}
```

**Comment by SmiteshP** [comment]
Hey!
Are you still facing this issue? Try keeping only nvim-navic as a component in lualine and then see if it is occuring?
What is the output for `lua require'lualine'.statusline()` ?

**Comment by SethBarberee** [comment]
This still happens for me. I tried deleting all components after nvim-navic (so it is the only component on the line) and it still appears.

**Comment by rodneykeeling** [comment]
I'm seeing this issue as well with lualine. It seems related to the padding. I have temporarily fixed this by applying a 0 padding on the right side after the navic output:
```lua
lualine_c = {
    { 'filetype' },
    { 'filename' },
    {
        navic.get_location,
        cond = navic.is_available,
        padding = { left = 1, right = 0 },
    }
}
```

**Comment by metaory** [comment]
issue is apparent specially on slanted styles

**Comment by SmiteshP** [comment]
Sorry for being so late, but I looked into this... And yep, its an issue with how lualine is handling the padding. For some reason it is applying incorrect colour for the space character in padding. Should be issue on lualine's repo.
