### ISSUE TITLE
Using codicons made it look unaligned 

### ISSUE THREAD

**Issue by augustocdias** [SmiteshP/nvim-navic#47]
When using codicons, the icons are placed unaligned with the text

![image](https://user-images.githubusercontent.com/1080789/183072165-a592e113-ab50-4284-aa78-2ab6f31b0e8d.png)

If I leave with the default icons, it looks good:

![image](https://user-images.githubusercontent.com/1080789/183072435-aba7afb8-9486-4b2d-af0f-8f72edc93ebe.png)

**Comment by SmiteshP** [comment]
There is nothing nvim-navic can do in this case... Its just an issue with the font you are using. Try using another font.
