### ISSUE TITLE
Invalid expression error inside Elixir function with map pattern matching as one of arguments

### ISSUE THREAD

**Issue by OMosk** [SmiteshP/nvim-navic#49]
Hi,

Really like your plugin but I encounter error when trying to navigate Elixir codebase, more specifically functions with pattern matching that involves maps as function arguments. I use your plugin in combination with LuaLine.

Elixir example to reproduce:
```elixir
defmodule S do
  def f("Elixir map syntax", %{"Key" => value}, is_it) do
  end
end
```
This example causes following error
```
E15: Invalid expression: "Key" => value
```

![Screenshot from 2022-08-19 00-20-21](https://user-images.githubusercontent.com/7224387/185505947-888c2924-cef4-4166-b035-f35462af266b.png)

My lualine config
```lua
config = function()
  local navic = require("nvim-navic")

  require('lualine').setup{
    options = {
      always_divide_middle = false,
      globalstatus = true,
    },
    tabline = {
      lualine_a = { {'tabs', max_length = function() return vim.o.columns * 0.66; end, mode = 2} },
      lualine_b = { { navic.get_location, cond = navic.is_available }, },
      lualine_z = { {'windows', mode = 0} },
    },
  }
end,
```

**Comment by SmiteshP** [comment]
Oh I see.. the `%{ }` pattern is being read by neovim as an expression to evaluate... Maybe filtering them out should help
