### ISSUE TITLE
Opening Ruby files gives error

### ISSUE THREAD

**Issue by prdanelli** [SmiteshP/nvim-navic#5]
Hello, I hope this is of use, otherwise I can try and provide more information. I opened a Ruby on Rails controller and saw the following error: 

```
Error executing vim.schedule lua callback: ...ite/pack/packer/start/nvim-navic/lua/nvim-navic/init.lua:30: attempt to index local 'scope' (a nil value)
stack traceback:
        ...ite/pack/packer/start/nvim-navic/lua/nvim-navic/init.lua:30: in function 'dfs'
        ...ite/pack/packer/start/nvim-navic/lua/nvim-navic/init.lua:50: in function 'parse'
        ...ite/pack/packer/start/nvim-navic/lua/nvim-navic/init.lua:59: in function 'handler'
        ...ite/pack/packer/start/nvim-navic/lua/nvim-navic/init.lua:13: in function 'callback'
        ...w/Cellar/neovim/0.7.0/share/nvim/runtime/lua/vim/lsp.lua:1535: in function 'handler'
        ...w/Cellar/neovim/0.7.0/share/nvim/runtime/lua/vim/lsp.lua:1025: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by SmiteshP** [comment]
Hey! Can you share which language server you are using? This seems similar to #2 
Probably your language server is following the old LSP specification.

**Comment by arsham** [comment]
It also happens on the HTML server version `4.2.1`, installed with the `nvim-lsp-installer` server.

**Comment by SmiteshP** [comment]
Hmm.. seems like a few of Language servers are still using the depreciated [SymbolInformation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolInformation) format.

For now, I will add a vim.notify for this error, indicating that server is using old LSP spec.

**Comment by prdanelli** [comment]
Not sure if you still need to know the language server, but it was Solargraph, the set up for which you can see here: 

https://github.com/prdanelli/dotfiles/blob/main/nvim/lua/lsp/config.lua#L30

**Comment by SmiteshP** [comment]
Closing this issue. Similar to #2 #15 .
Language servers that aren't using documentSymbols will not work with navic. Added error message for this.
