### ISSUE TITLE
[Feature Request] Show function-parameter types

### ISSUE THREAD

**Issue by LukasPietzschmann** [SmiteshP/nvim-navic#54]
I previously used `nvim-treesitter` to display the current function I'm in:
```
local f = require'nvim-treesitter'.statusline({
    indicator_size = 300,
    type_patterns = {"class", "function", "method", "interface", "type_spec"}
})
```
This did not only display the function's name, but also it's parameters.
![Screenshot from 2022-09-03 10-41-26](https://user-images.githubusercontent.com/49213919/188263155-4a89d10a-937b-4990-8525-363e838e92ed.png)

Is there a way to achieve this behavior with `nvim-navic`?

**Comment by SmiteshP** [comment]
There is no way to get this behavior with navic..
I aim to replicate the VSCodes breadcrumb line with this plugin and it doesn't show this information. Also I think having parameters would be too verbose.
