### ISSUE TITLE
Not working with remark_ls

### ISSUE THREAD

**Issue by ignamartinoli** [SmiteshP/nvim-navic#61]
Hi,
in **Markdown** files, using `remark_ls` as server, I can't get any result to show in the winbar, which is weird since I was able to do it with `aerial.nvim`.

**Comment by SmiteshP** [comment]
Looking at the code of aerial.nvim seems like they have added a dedicated code to handle output from this lsp. I am not keen on adding this though as markdown isn't a programming language.

**Comment by ignamartinoli** [comment]
based :+1:
