### ISSUE TITLE
Bug: Strange error when scrolling through a line containing substring `['%']`?

### ISSUE THREAD

**Issue by nyngwang** [SmiteshP/nvim-navic#65]
Moving from upstream issue: https://github.com/nvim-lualine/lualine.nvim/issues/873

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

1. You will need to create a lua file, with lua LSP Client sumneko/lua-language-server attached.
2. The lua file should contain a lua table like this:
    ```lua
    window = {
      mappings = {
        -- root behaviour.
        ['-'] = 'navigate_up',
        ['<C-]>'] = 'set_root',
    
        -- tree itself.
        ['R'] = 'refresh',
    
        -- open files.
        ['<2-LeftMouse>'] = 'shift_M_open',
        ['<cr>'] = 'shift_M_open',
        ['w'] = 'picker_open',
        ['o'] = 'macOS_open',
        ['%'] = 'open_vsplit', -- THIS LINE TO BE SPECIFIC
      }
    }
    ```
3. Move your cursor upward until it is located at the line containing the substring `['%']`.

### Expected behaviour
Do nothing.

### Actual behaviour
An error occurred:

```
Error executing vim.schedule lua callback: ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:77: E539: Illegal character <'>
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:77: in function 'setter_fn'
        ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:50: in function 'set_opt'
        ...acker/start/lualine.nvim/lua/lualine/utils/nvim_opts.lua:74: in function 'set'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:422: in function 'refresh'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:343: in function <...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:342>
Press ENTER or type command to continue
```

### Minimal config to reproduce the issue

```lua
use {
  'nvim-lualine/lualine.nvim',
  requires = {
    'kyazdani42/nvim-web-devicons',
    {
      'SmiteshP/nvim-navic',
      requires = 'neovim/nvim-lspconfig',
      config = function () require('nvim-navic').setup{ separator = '  ' } end
    }
  },
  config = function ()
    local navic = require('nvim-navic')
    require('lualine').setup {
      options = {
        theme = 'palenight', -- Purple
      },
      sections = {
        lualine_c = { 'filename', { navic.get_location, cond = navic.is_available } },
        lualine_x = { 'encoding', 'filetype' },
      }
    }
  end
}
```

### Aditional information

Reasoning: I guess the char `%` might have a special meaning to the next char that follow, thus causing the error. E.g. it escapes the single quote `'`.

**update**: This guess got confirmed by the author of lualine.nvim, see [here](https://github.com/nvim-lualine/lualine.nvim/issues/873#issuecomment-1283987785).

<img src="https://user-images.githubusercontent.com/24765272/196693073-aa45ea37-ce5e-48be-80f5-3fc52b148e88.png" width="500">

and if you look closely, you will also find that the left-curly-braces, i.e. `{`s, showing in the image is bolded: (ignoring the cat which is from another desktop program.)

<img src="https://user-images.githubusercontent.com/24765272/196697501-e4bd2704-5615-4905-a5c0-07726d631dab.png" width="1200">

**Comment by nyngwang** [comment]
**update**: This guess got confirmed by the author of lualine.nvim, see [here](https://github.com/nvim-lualine/lualine.nvim/issues/873#issuecomment-1283987785).

**Comment by nyngwang** [comment]
@SmiteshP Hi, sorry for tagging you on a closed issue first. But it seems that the problem of bolded left-curly-brace still exists: 

<img src="https://user-images.githubusercontent.com/24765272/211309955-663ef469-22f3-4a99-8bd5-ebdfa7f4e975.png" width="500">

(sorry for making the two arrows exaggeratedly bolded. I did this because I think it would be more easily seen by **any** readers. might be offensive for some people so I put a note here.)

**Comment by SmiteshP** [comment]
Can you paste the output of `get_location` and `get_data` over here?

**Comment by SmiteshP** [comment]
Looking at the photo, that icon looks to be unicode U+F668 (which is default setting of navic).
I don't think any special characters like '%' or curly braces would affect to make half of a unicode character to be bold. Could be an issue with the font or the terminal emulator maybe.
Try pasting [U+F668](https://unicode-table.com/en/search/?q=U%2BF668) in the neovim buffer as well and see if it looks similar.

**Comment by nyngwang** [comment]
> Please paste the output of `get_location` and `get_data` over here.

@SmiteshP This is the result of calling `get_location()`. (I never use `get_data`)

```
21:30:39 msg_show  return   use   config   vim.api.nvim_create_autocmd   callback   if   vim.wo.winbar
21:30:40 msg_show  return   use   config   vim.api.nvim_create_autocmd   callback
21:30:40 msg_show  return   use   config   vim.api.nvim_create_autocmd   callback   if   vim.wo.winbar
```
