### ISSUE TITLE
Feature: Throttle updates during CursorMove

### ISSUE THREAD

**Issue by chase** [SmiteshP/nvim-navic#66]
On sufficiently large codebases (like Electron/Chromium), there's a noticeable delay when moving the cursor repeatedly (such as holding down j or k).

Adding a configurable throttle would likely solve this.

You can find an MIT-licensed implementation of throttle/debounce for NeoVim here: https://gist.github.com/runiq/31aa5c4bf00f8e0843cd267880117201

---

A more dynamic way of solving this would be to:
1. Measure the time taken to update,
2. Take the average of the update times
3. Throttle based on this average

**Comment by chase** [comment]
Actually, this seems to only be a problem in LunarVim when a config is reloaded multiple time but autocommands aren't cleared. My apologies! Thanks for the nice plugin 🙂

**Comment by liujoey** [comment]
I would suggest to reopen this, today I was editing a java file with very large class document (a very long comment right before the class), when the comment section is in the view, moving cursor (with j and k, w, etc) becomes extremely slow, even cause the terminal to halt for few seconds. I have to completely disable nvim-navic.
