### ISSUE TITLE
ERROR: server doesn't support documentSymbols

### ISSUE THREAD

**Issue by ahhshm** [SmiteshP/nvim-navic#7]
When I open a typescript-react (tsx) file I get these errors:
```
nvim-navic: Server eslint does not support documentSymbols
nvim-navic: Server tailwindcss does not support documentSymbols
```
and it stops working which is wired because it should at least attach to `tsserver`.

Also, is that possible to disable this kind of error? I don't want to get an error every time I open a typescript file.

**Comment by SmiteshP** [comment]
> Also, is that possible to disable this kind of error? I don't want to get an error every time I open a typescript file.

This error is there to inform users that this lsp-server won't work with nvim-navic, as it is incapable of providing required information. So that you can remove it from your `on_attach` function while you setup your lsp server.

**Comment by ahhshm** [comment]
Ok, so `tailwindcss` and `eslint` can't provide it required information. But I also have `tsserver` setup so why it doesn't work?

I've also tried this to prevent setting up this plugin for servers that don't support documentSymbols:
```lua
  if client.server_capabilities.documentSymbolProvider then
    navic.attach(client, bufnr)
  end
```
But it also doesn't work.

btw, I'm using your feline example and my plugins are up to date.

**Comment by RaafatTurki** [comment]
@SmiteshP
I suggest a configurable approach, something like silent=true should omit printing both the

"does not support documentSymbols, it is responds with SymbolInformation format which has been deprecated in latest LSP specification"
and
"does not support documentSymbols"
errors

Let me know what you think and I'll PR it

**Comment by luisvgs** [comment]
Any workaround for this? I'm having the same issue. `Sever null-ls does not support documentSymbols`

**Comment by SmiteshP** [comment]
>I've also tried this to prevent setting up this plugin for servers that don't support documentSymbols:
>
> ```
> if client.server_capabilities.documentSymbolProvider then
>   navic.attach(client, bufnr)
> end
> ```

Why would you need this if else statement? Once you determine that nvim-navic won't work with a certain LSP, just don't pass the attach function to it.

>I suggest a configurable approach, something like silent=true should omit printing both the

That can be done, but I don't see a point for this. Once a user sees the error, they can simply go and remove the attach function and solve it.

**Comment by SmiteshP** [comment]
> Any workaround for this? I'm having the same issue. Sever null-ls does not support documentSymbols

There is no workaround for this. It means that null-ls is not capable of providing information that nvim-navic uses. You should look for alternate language server for that language or maybe open an issue on their repository to support documentSymbols.

**Comment by SmiteshP** [comment]
> There should be a way to ignore language servers that don't support documentSymbols.

But if you just don't pass navic to these lsp servers, you won't get the error.
So in your config where you are setting up lsp server it should look something like this..

```lua
require("lsp-config").tsserver.setup({
    -- Other settings here
    on_attach = function(client, bufnr) require("nvim-navic").attach(client, bufnr) end
})

require("lsp-config").eslint.setup({
    -- Some settings here
    -- Don't pass navic to on_attach here!
})
```

**Comment by ahhshm** [comment]
Yeah you are right. I had a very stupid mistake in my configuration. Sorry for that
