### ISSUE TITLE
Where is `->` coming from and how do I remove it?

### ISSUE THREAD

**Issue by miversen33** [SmiteshP/nvim-navic#78]
I am setting up `nvim-navic` (super nice plugin by the way!) and I can't seem to figure out why some of the data being kicked back has a `->` in it. Below is an image to helps how what I am seeing

![image](https://user-images.githubusercontent.com/2640668/206860445-6a3a65ff-9689-41f3-a9d6-a4cb85a0da62.png)

The string for this is
```
 import -> >  import -> 
```

I am not doing anything crazy with the formatting of the string, below is the function I am using
```lua
    local create_symbol_bar = function()
        if not nvim_navic.is_available() then
            return ''
        end
        local details = {}
        for _, item in ipairs(nvim_navic.get_data()) do
            table.insert(details, item.icon .. item.name)
        end
        return table.concat(details, ' > ')
    end
```

It seems to only be present in an anon function, though not _always_ present in the anon function. Additionally, it seems to be related to lua.

When I dump the return contents of `get_data`, I am seeing the following table
```
{
  icon = " ",
  kind = 12,
  name = "import ->",
  scope = {
    ["end"] = {
      character = 3,
      line = 326
    },
    start = {
      character = 45,
      line = 224
    }
  },
  type = "Function"
}
```
Notice that the `name` itself is including `->`. Any idea what could be causing this?
I am editing [this file](https://github.com/miversen33/miversen-dotfiles/blob/25386b7772e6639902df0ed917b63289a4a99588/editors/nvim/lua/plugins.lua) if you want to pull it down, open it and see if `navic` is returning the same odd character artifacts in the `name` for you.

I will see if I can get a minimal config put together to reflect this, though as navic is just using the LSP and the currently open file, I don't imagine my neovim config is doing much to affect this.

Some quick info about my setup
```bash
$ nvim --version
NVIM v0.8.0-dev-1008-g12fe197cf
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/miversen/git/neovim/build/cmake.config -I/home/miversen/git/neovim/src -I/home/miversen/git/neovim/.deps/usr/include -I/usr/include -I/home/miversen/git/neovim/build/src/nvim/auto -I/home/miversen/git/neovim/build/include
Compiled by miversen

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/neovim/share/nvim"

Run :checkhealth for more info
```

```bash
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

**Comment by gegoune** [comment]
Search closed issues, that has been discussed before. I think this is sumneko's lsp behaviour.

**Comment by miversen33** [comment]
> Search closed issues, that has been discussed before. I think this is sumneko's lsp behaviour.

I did a quick search but didn't see anything.

It looks like it was discussed [here](https://github.com/SmiteshP/nvim-navic/issues/63#issuecomment-1290829057). Knowing this is an LSP issue, I'll accept that I need to do some string manipulation. I wonder if it makes sense to call this out as a known "issue" so people don't keep submitting issues for it

**Comment by SmiteshP** [comment]
Duplicate #63
