### ISSUE TITLE
Bug: new condition:is_available(_bufnr_) parameter isn't really optional

### ISSUE THREAD

**Issue by joehannes** [SmiteshP/nvim-navic#88]
Hey :-)

Latest update broke my setup.
Investigating the help I was confused, because the new "bufnr" parameter is said to be optional (with default current) ...
but, that seems not to be the case, nvim throwing errors instead and not displaying the winbar at all.

Using vim.api.nvim_get_current_buf() as a quickfix works:
* no more error msgs
* Navic UI back

Cheers, J

**Comment by SmiteshP** [comment]
It is optional. The function is checking if the variable is set or not, if not it is using nvim_get_current_buf()
Are you using heirline maybe? their was another issue that mentioned an issue occured with heirline because it was passing a table to available function by itself.

```lua
function M.is_available(bufnr)
	bufnr = bufnr or vim.api.nvim_get_current_buf()
	return vim.b[bufnr].navic_client_id ~= nil
end
```

**Comment by SmiteshP** [comment]
Refer to #87

**Comment by SmiteshP** [comment]
Opened pull request to update this documentation on heirline.
https://github.com/rebelot/heirline.nvim/pull/126
