### ISSUE TITLE
Provide the item kind as a string in `get_data`

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-navic#9]
Currently, `get_data` returns `{ name = <string>, kind = <number> }`. This number appears to relate primarily to how things are managed internally i.e. `Type` mapping to 3 or something, for any user seeking to use this function they have to map this value back to a string, so they can create highlights or find the icon in a map somewhere. So short of copying the exact order in the codebase, it's hard to work with these numbers. They could also relate to some internal neovim ordering, but this isn't very clear i.e. where or what this ordering is, so I think the string would still be preferable.

**Comment by MordechaiHadad** [comment]
Please also provide the icon like nvim-gps!

**Comment by SmiteshP** [comment]
Yeah sure! I should have though of this earlier 😆

**Comment by SmiteshP** [comment]
Done!
