### ISSUE TITLE
Dockerfile icons was not recognized

### ISSUE THREAD

**Issue by adriancmiranda** [SmiteshP/nvim-navic#91]
I don't know, but probably because there isn't an extension for Dockerfile files, the `nvim-navic` doesn't recognize the icon that I had to override at `nvim-web-devicons`

> Dockerfile
![image](https://user-images.githubusercontent.com/5431310/220627325-9aefb016-fbf6-4415-8bd7-07644f896006.png)

> docker-compose.yml
![image](https://user-images.githubusercontent.com/5431310/220628838-bd71bf46-b159-436f-af64-2eb95c8625d2.png)

```lua
local nvim_web_devicons = require('nvim-web-devicons')
nvim_web_devicons.setup({
  color_icons = true,
  default = true,
  strict = true,
})

nvim_web_devicons.set_icon({
  ['Dockerfile'] = {
	  name = 'Docker',
	  color = '#086DD7',
	  icon = '',
  },
  ['docker-compose.yml'] = {
	  name = 'DockerCompose',
	  color = '#086DD7',
	  icon = '',
  },
})

local nvim_navic = require('nvim-navic')
nvim_navic.setup({
  highlight = true,
  safe_output = true,
  depth_limit = 0,
  depth_limit_indicator = '..',
  separator = ' > ',
})
```

I have not sure if it is related specifically to `nvim-navic`, but, it's the `nvim-navic` that does not recognize them, so...

**Comment by SmiteshP** [comment]
Its not related to nvim-navic. The symbol isn't showing up because its not present in your font. Try pasting the same symbol in your terminal and see that its shown as same hexadecimal box.
Try using font patched with nerd fonts, it tends to have all the symbols most people need.

**Comment by adriancmiranda** [comment]
Ok, but, do you notice that works everywhere? Bufferline, Nvim-tree, lir, inside of buffer...I mean, doesn't seem that it's a font problem. But ok, I can handle it

**Comment by SmiteshP** [comment]
Are you sure its the same icon? because nvim-navic isn't responsible for rendering icons and stuff. It just gives out string output, and for icons it will just output the unicode character for that icon. Then its upto the terminal emulator on how it displays it.

**Comment by adriancmiranda** [comment]
Actually, I saw the `nvim-navic` code for a while, trying to understand the difference, and, I have not sure, but I tried to make what you said, I opened the font (the icon was there), but I installed it again with no success yet. I'll put more effort into, understanding this over the weekend before coming back here.
