### ISSUE TITLE
Recent update breaks markdown files without headings

### ISSUE THREAD

**Issue by chrisgrieser** [SmiteshP/nvim-navic#99]
As far as I can tell, markdown files without headings always get this error, popping up every half second (updatetime, I assume), making these buffers unusable. Had to disable navic for markdown.

![CleanShot 2023-03-26 at 22 55 58](https://user-images.githubusercontent.com/73286100/227804217-97eee02a-e98d-4a95-99f5-7b83ea5a26c6.png)

**Comment by mischavandenburg** [comment]
I have the same issue for nearly empty files or bash scripts of only a few lines.

**Comment by ueaner** [comment]
Update to [ec0ae4a](https://github.com/SmiteshP/nvim-navic/commit/ec0ae4a3855ede3f7c412b6823f14978179828a5) , have the same issue, temporarily rolled back to [59b997f](https://github.com/SmiteshP/nvim-navic/commit/59b997feb5915b8dbcbe5f34b07b12de332ea9de)

**Comment by SmiteshP** [comment]
@chrisgrieser @mischavandenburg @ueaner 
Can you guys share some minimal examples where you are seeing this issue and which LSP you are using for that file?

**Comment by SmiteshP** [comment]
Looks like the issue was occuring on line 325, perhaps this PR #100 has already fixed it 🤔 
Can you guys check if latest commit is working?

**Comment by ueaner** [comment]
@SmiteshP Thanks, this works for me.

**Comment by chrisgrieser** [comment]
yep, the latest seems to have fixed it. Thanks!
